; PlatformIO Project Configuration File
; Projeto: autonomous-car — Carro autônomo com Arduino Mega 2560 + Gravity HuskyLens
;
; Documentação: https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = megaatmega2560

[env:megaatmega2560]
platform  = atmelavr
board     = megaatmega2560
framework = arduino

; Velocidade do monitor serial (depuração)
monitor_speed = 115200

; Bibliotecas externas
;  - DFRobot HUSKYLENS: comunicação com a Gravity HuskyLens (I2C/UART)
;  - NewPing: leitura estável do sensor ultrassônico HC-SR04
lib_deps =
    dfrobot/HUSKYLENS@^0.3.10
    teckel12/NewPing@^1.9.7

; Flags de build (opcional)
build_flags =
    -Wall
